// GENERATED from scripts/data/beta-world.json (tora-backend) — edit there and regenerate.
// Beta-only strings in all 8 app languages (EN generated, the rest adapted by hand). Deleted after launch.
export const BETA_TASKS_EN = {
 "T01": {
  "title": "Add TORA to your phone home screen.",
  "hint": "iPhone: open beta.torahub.io in Safari, tap the share icon, then Add to Home Screen. Android and desktop: tap the install icon in the address bar."
 },
 "T02": {
  "title": "Sign in with the invitation code from your email.",
  "hint": "Open the email, tap the button, paste the code, choose a password."
 },
 "T03": {
  "title": "Log out, then log back in.",
  "hint": "Settings, scroll to the bottom, Log out."
 },
 "T04": {
  "title": "Create your second profile.",
  "hint": "Tap your profile picture at the top, then Add profile. Pick the second role you were assigned."
 },
 "T05": {
  "title": "Complete your profile: bio, genres, city, and at least two links.",
  "hint": "Profile, then Edit."
 },
 "T06": {
  "title": "Upload a profile photo.",
  "hint": "Profile, Edit, tap the picture."
 },
 "T07": {
  "title": "Mark your available dates for the next two months.",
  "hint": "Profile > Manage > Calendar. Tap the dates you are free."
 },
 "T08": {
  "title": "Update your travel schedule.",
  "hint": "Profile > Manage > Travel Schedule. Add a city and the dates you will be there."
 },
 "T09": {
  "title": "Change the app language, then change it back to the one you prefer.",
  "hint": "Settings > Language."
 },
 "T10": {
  "title": "Verify your Instagram handle.",
  "hint": "Profile, tap the unverified banner, copy the code, send it as a DM to @tora.verify."
 },
 "T11": {
  "title": "Open the globe in Search and tap a city to see who is there.",
  "hint": "Search tab, Globe view. Pins show where members are — tap one to open that city. The city filter in list view works too."
 },
 "T12": {
  "title": "Like another profile.",
  "hint": "Tap the heart on a profile card."
 },
 "T13": {
  "title": "Send a connection request to your assigned contact.",
  "hint": "Open their profile, tap Connect, write a short message."
 },
 "T14": {
  "title": "Send a message to a connection.",
  "hint": "Messages tab, or the message button on their profile."
 },
 "T15": {
  "title": "Send a file in a chat. Any attachment is fine.",
  "hint": "Paperclip in the chat bar."
 },
 "T16": {
  "title": "Send an offer to your assigned contact.",
  "hint": "Open their profile or your chat with them, then Make an Offer."
 },
 "T17": {
  "title": "Send an offer that includes a deposit deadline and a final payment deadline.",
  "hint": "The two date fields near the bottom of the offer form."
 },
 "T18": {
  "title": "Open the offer waiting for you and read the terms.",
  "hint": "Bookings tab. It is at the top."
 },
 "T19": {
  "title": "Counter an offer, changing the fee and at least one other term.",
  "hint": "Open the offer, tap Counter."
 },
 "T20": {
  "title": "Accept an offer.",
  "hint": "Review Offer, then Accept."
 },
 "T21": {
  "title": "Decline an offer and write the reason.",
  "hint": "Review Offer, then Decline."
 },
 "T22": {
  "title": "Send a contract for a deal you agreed. Any attachment is fine.",
  "hint": "Open the accepted booking, tap Send Contract, upload any file."
 },
 "T23": {
  "title": "Sign a contract someone sent you.",
  "hint": "Open the booking, tap Sign."
 },
 "T24": {
  "title": "Skip the contract step, then restore it.",
  "hint": "Skip Contract on the booking card, then Restore Contract Step."
 },
 "T25": {
  "title": "Mark a deposit as sent and attach a receipt. Any image or PDF is fine.",
  "hint": "Payment step on the booking card."
 },
 "T26": {
  "title": "Confirm you received the payment.",
  "hint": "Payment step on the booking card."
 },
 "T27": {
  "title": "Take one booking all the way through, from the first message to fully confirmed and paid.",
  "hint": "No shortcut on this one. It is the whole product."
 },
 "T28": {
  "title": "Accept the agent who asked to represent you.",
  "hint": "Notifications, or the chat with that agent."
 },
 "T29": {
  "title": "Upload your press kit and your technical rider. Any file is fine.",
  "hint": "Chat paperclip, or the Documents step inside a booking."
 },
 "T30": {
  "title": "Add three artists to your roster.",
  "hint": "Profile > Represented Artists > Add. Search TORA or type them in manually."
 },
 "T31": {
  "title": "Send a representation request to an artist on TORA.",
  "hint": "Their profile, Request Representation."
 },
 "T32": {
  "title": "Open Manage Artist and act on one item in the action list.",
  "hint": "Roster, tap Manage on an artist. The list is at the top."
 },
 "T33": {
  "title": "Negotiate a booking on behalf of an artist you represent, rather than as yourself.",
  "hint": "Switch the offer context to the artist when you respond."
 },
 "T34": {
  "title": "Pitch one of your artists to a venue by message. Venues do not receive offers, they send them.",
  "hint": "Open the venue profile and tap Send a pitch. If the venue is interested they will send you an offer back."
 },
 "T35": {
  "title": "Reply to a pitch that came in by message by sending an offer.",
  "hint": "Open the chat, then Make an Offer from that conversation."
 },
 "T36": {
  "title": "Open a tour in Tour Kickstart and tap I'm interested.",
  "hint": "Tour tab > Tour Kickstart. One tap — the artist sees interest building city by city. Liking a touring artist also sets up a travel alert for you automatically."
 },
 "T37": {
  "title": "Propose a date on someone's tour.",
  "hint": "Explore > Tours, open a tour, Propose Date."
 },
 "T39": {
  "title": "Set your capacity and your venue details.",
  "hint": "Profile > Edit. Capacity, city, genres, photos."
 },
 "T40": {
  "title": "Share your technical spec and hospitality info with an artist. Any file is fine.",
  "hint": "Chat paperclip, or the Documents step in a booking."
 },
 "T41": {
  "title": "Post something in News.",
  "hint": "News tab, composer at the top."
 },
 "T42": {
  "title": "Like or comment on someone else's post.",
  "hint": "The heart or the comment icon on any post."
 },
 "T43": {
  "title": "Turn on notifications, then confirm one reaches you.",
  "hint": "The card that appears after login, or Settings > Notifications. On iPhone you must add TORA to your home screen first (task T01)."
 },
 "T45": {
  "title": "Upgrade to Premium using the test card 4242 4242 4242 4242, any future expiry, any CVC.",
  "hint": "Settings > Premium, or the prompt that appears when you hit a limit."
 },
 "T46": {
  "title": "Cancel your subscription, then check what the app tells you about the date your access ends.",
  "hint": "Settings > Manage subscription > Cancel."
 },
 "T07@AGENT": {
  "title": "Mark available dates for one of your artists for the next two months.",
  "hint": "Profile > Manage > pick your artist > Calendar. Tap the dates they are free."
 },
 "T08@AGENT": {
  "title": "Update the travel schedule of one of your artists.",
  "hint": "Profile > Manage > pick your artist > Travel Schedule. Add a city and the dates."
 },
 "T51": {
  "title": "Final check: would you run a real booking through TORA next month? Yes or no, and why.",
  "hint": "Tap Answer. One sentence is enough."
 }
};

// Sheet UI strings — EN default; JA below, the other six are appended at the end of this file.
export const BETA_UI = {
  en: {
    yourList: 'YOUR LIST', tellUs: 'TELL US',
    intro: 'Work through these in any order, over as many sittings as you like.',
    showMeHow: 'Show me how', confusing: 'This was confusing', skip: 'Skip', answer: 'Answer',
    skipWhy: 'Why are you skipping it? One line is enough.', cancel: 'Cancel', skipIt: 'Skip it',
    typeQ: 'What kind of thing?', howBad: 'How bad?',
    placeholder: 'What happened? Short and blunt is perfect — "no idea what this button does" is a useful report.',
    addShot: 'Add screenshot', autoNote: 'Your screen, device and the last error are attached automatically — no need to describe them.',
    send: 'Send', received: 'Received — thank you.', receivedSub: 'Every report makes TORA better. Send as many as you like.',
    sendAnother: 'Send another', aboutTask: 'About task', remove: 'remove', loading: 'Loading…',
    loadError: 'Could not load your list.', retry: 'Retry',
    severities: { blocked: 'Blocked me', annoyed: 'Annoyed me', noting: 'Just noting it' },
    inviteUnavailable: 'Not available during beta testing — the beta is a closed group. Inviting friends unlocks at launch.',
    finalCheck: 'FINAL CHECK', finalIntro: 'One question, straight from the founder. Your honest answer shapes what we build next.',
    yes: 'Yes', no: 'No', whyQ: 'Why?', whyPlaceholder: 'One sentence is enough. Blunt is good.',
    finalSend: 'Send my answer', finalDone: 'Thank you — that is the one answer we needed.', finalDoneSub: 'Your list is complete. You can still send reports from Tell Us any time.',
    backToList: 'Back to your list',
  },
  ja: {
    yourList: 'タスク', tellUs: '報告',
    intro: '順番は自由です。数分の空き時間に少しずつ進めてください。',
    showMeHow: 'やり方を見る', confusing: '分かりにくかった', skip: 'スキップ', answer: '回答する',
    skipWhy: 'スキップする理由を一言どうぞ。', cancel: 'キャンセル', skipIt: 'スキップする',
    typeQ: 'どんな内容ですか？', howBad: '深刻度は？',
    placeholder: '何が起きましたか？短く率直で十分です──「このボタンが何をするのか分からない」も立派な報告です。',
    addShot: 'スクリーンショットを追加', autoNote: '画面・端末・直近のエラーは自動で添付されます。説明は不要です。',
    send: '送信', received: '受け取りました — ありがとうございます。', receivedSub: 'すべての報告がTORAを良くします。何件でもどうぞ。',
    sendAnother: 'もう1件送る', aboutTask: '対象タスク', remove: '外す', loading: '読み込み中…',
    loadError: 'リストを読み込めませんでした。', retry: '再試行',
    severities: { blocked: '操作できなくなった', annoyed: '不便だった', noting: 'メモ程度' },
    inviteUnavailable: 'ベータテスト中はご利用いただけません。ベータは限定グループのため、友達招待はローンチ時に解放されます。',
    finalCheck: '最終確認', finalIntro: '創業者からの質問はひとつだけ。率直な回答が次に作るものを決めます。',
    yes: 'はい', no: 'いいえ', whyQ: '理由は？', whyPlaceholder: '一文で十分です。率直にどうぞ。',
    finalSend: '回答を送る', finalDone: 'ありがとうございます — これが一番知りたかった答えです。', finalDoneSub: 'リストは完了です。「報告」からはいつでも送れます。',
    backToList: 'リストに戻る',
  },
};

// JA pass (Build Item 8): adapted, not machine-translated. Venue = ベニュー;
// TORA, Premium and role names stay in English. Flag for Alessandro's
// native review before Wave 2.
export const BETA_TASKS_JA = {
 T01: { title: 'TORAをスマホのホーム画面に追加する。', hint: 'iPhone: Safariで beta.torahub.io を開き、共有アイコン →「ホーム画面に追加」。Android・PC: アドレスバーのインストールアイコンをタップ。' },
 T02: { title: 'メールの招待コードでサインインする。', hint: 'メールを開いてボタンをタップし、コードを貼り付けてパスワードを設定します。' },
 T03: { title: 'ログアウトして、もう一度ログインする。', hint: '設定を一番下までスクロールして「ログアウト」。' },
 T04: { title: '2つ目のプロフィールを作成する。', hint: '上部のプロフィール写真をタップ →「プロフィールを追加」。割り当てられた2つ目のロールを選びます。' },
 T05: { title: 'プロフィールを完成させる: 自己紹介・ジャンル・都市・リンク2つ以上。', hint: 'プロフィール → 編集。' },
 T06: { title: 'プロフィール写真をアップロードする。', hint: 'プロフィール → 編集 → 写真をタップ。' },
 T07: { title: '今後2か月の空き日程を登録する。', hint: 'プロフィール → 管理 → カレンダー。空いている日をタップします。' },
 T08: { title: '渡航スケジュールを更新する。', hint: 'プロフィール → 管理 → 渡航スケジュール。都市と滞在日程を追加します。' },
 T09: { title: 'アプリの言語を切り替えて、また元に戻す。', hint: '設定 → 言語。' },
 T10: { title: 'Instagramアカウントを認証する。', hint: 'プロフィールの未認証バナーをタップし、コードをコピーして @tora.verify にDMで送ります。' },
 T11: { title: 'Searchのグローブを開き、都市をタップしてその街のメンバーを見る。', hint: 'Searchタブのグローブ表示。ピンはメンバーがいる都市です。タップするとその街が開きます。リスト表示の都市フィルターでも構いません。' },
 T12: { title: '他のプロフィールにいいねする。', hint: 'プロフィールカードのハートをタップ。' },
 T13: { title: '担当の相手にコネクション申請を送る。', hint: '相手のプロフィールを開き「つながる」をタップして、短いメッセージを書きます。' },
 T14: { title: 'コネクションにメッセージを送る。', hint: 'メッセージタブ、またはプロフィールのメッセージボタンから。' },
 T15: { title: 'チャットでファイルを送る。どんな添付でもOK。', hint: 'チャット入力欄のクリップアイコン。' },
 T16: { title: '担当の相手にオファーを送る。', hint: '相手のプロフィールかチャットを開いて「オファーを作成」。' },
 T17: { title: 'デポジット期限と最終支払い期限を含むオファーを送る。', hint: 'オファーフォーム下部の2つの日付欄です。' },
 T18: { title: '届いているオファーを開いて条件を読む。', hint: 'ブッキングタブの一番上にあります。' },
 T19: { title: 'オファーにカウンターする。フィーともう1つ以上の条件を変える。', hint: 'オファーを開いて「カウンター」をタップ。' },
 T20: { title: 'オファーを承諾する。', hint: 'オファーを確認して「承諾」。' },
 T21: { title: 'オファーを断り、理由を書く。', hint: 'オファーを確認して「辞退」。' },
 T22: { title: '合意した取引の契約書を送る。どんなファイルでもOK。', hint: '承諾済みのブッキングを開き「契約書を送る」→ 任意のファイルをアップロード。' },
 T23: { title: '送られてきた契約書に署名する。', hint: 'ブッキングを開いて「署名」をタップ。' },
 T24: { title: '契約ステップをスキップして、その後復元する。', hint: 'ブッキングカードの「契約をスキップ」→「契約ステップを復元」。' },
 T25: { title: 'デポジットを送金済みにして領収書を添付する。画像でもPDFでもOK。', hint: 'ブッキングカードの支払いステップから。' },
 T26: { title: '支払いの受領を確認する。', hint: 'ブッキングカードの支払いステップから。' },
 T27: { title: '最初のメッセージから支払い完了まで、ブッキングを最後までやり切る。', hint: 'これに近道はありません。プロダクトそのものです。' },
 T28: { title: '代理を申し出たエージェントを承諾する。', hint: '通知、またはそのエージェントとのチャットから。' },
 T29: { title: 'プレスキットとテクニカルライダーをアップロードする。どんなファイルでもOK。', hint: 'チャットのクリップ、またはブッキング内の書類ステップから。' },
 T30: { title: 'ロースターにアーティストを3人追加する。', hint: 'プロフィール → 所属アーティスト → 追加。TORA内を検索するか手入力します。' },
 T31: { title: 'TORA上のアーティストに代理申請を送る。', hint: '相手のプロフィールで「代理を申請」。' },
 T32: { title: 'アーティスト管理を開き、アクションリストの項目を1つ処理する。', hint: 'ロースターでアーティストの「管理」をタップ。リストは上部にあります。' },
 T33: { title: '自分としてではなく、担当アーティストの代理でブッキングを交渉する。', hint: '返信時にオファーの主体をアーティストに切り替えます。' },
 T34: { title: '担当アーティストをベニューにメッセージでピッチする。ベニューはオファーを受け取らず、送る側です。', hint: 'ベニューのプロフィールを開いて「ピッチを送る」。興味があればオファーが返ってきます。' },
 T35: { title: 'メッセージで届いたピッチに、オファーを送って返答する。', hint: 'チャットを開き、その会話から「オファーを作成」。' },
 T36: { title: 'Tour Kickstartでツアーを開き、「興味を示す」をタップする。', hint: 'Tourタブ > Tour Kickstart。ワンタップで興味を伝えられます。ツアー中のアーティストにいいねすると、渡航アラートも自動で設定されます。' },
 T37: { title: '誰かのツアーに日程を提案する。', hint: 'ツアーを開いて「日程を提案」。' },
 T39: { title: 'キャパシティとベニュー情報を設定する。', hint: 'プロフィール → 編集。キャパシティ・都市・ジャンル・写真。' },
 T40: { title: 'テクニカル仕様とホスピタリティ情報をアーティストに共有する。どんなファイルでもOK。', hint: 'チャットのクリップ、またはブッキング内の書類ステップから。' },
 T41: { title: 'Newsに何か投稿する。', hint: 'Newsタブ上部の投稿欄から。' },
 T42: { title: '他の人の投稿にいいねかコメントをする。', hint: '投稿のハートまたはコメントアイコン。' },
 T43: { title: '通知をオンにして、1件届くことを確認する。', hint: 'ログイン後に表示されるカード、または設定 → 通知。iPhoneは先にホーム画面への追加が必要です（タスクT01）。' },
 T45: { title: 'テストカード 4242 4242 4242 4242（期限・CVCは任意）でPremiumにアップグレードする。', hint: '設定 → Premium、または上限に達したときに表示される案内から。' },
 T46: { title: 'サブスクリプションを解約し、アクセス終了日について何と表示されるか確認する。', hint: '設定 → サブスクリプション管理 → 解約。' },
 'T07@AGENT': { title: '担当アーティストの今後2か月の空き日程を登録する。', hint: 'プロフィール > Manage > アーティストを選択 > カレンダー。' },
 'T08@AGENT': { title: '担当アーティストの渡航スケジュールを更新する。', hint: 'プロフィール > Manage > アーティストを選択 > 渡航スケジュール。' },
 T51: { title: '最終確認: 来月、実際のブッキングをTORAで行いますか？はい/いいえと、その理由。', hint: '「回答する」をタップ。一文で十分です。' },
};

// Six more languages (2026-09-03): adapted like the JA pass. TORA, Premium,
// role names and the tab names the app itself leaves in English stay as-is.
export const BETA_TASKS_BY_LANG = {
  ja: BETA_TASKS_JA,
  it: {
    T01: { title: 'Aggiungi TORA alla schermata Home del telefono.', hint: 'iPhone: apri beta.torahub.io in Safari, tocca l\'icona di condivisione, poi "Aggiungi alla schermata Home". Android e desktop: tocca l\'icona di installazione nella barra degli indirizzi.' },
    T02: { title: 'Accedi con il codice di invito ricevuto via email.', hint: 'Apri l\'email, tocca il pulsante, incolla il codice, scegli una password.' },
    T03: { title: 'Esci e poi accedi di nuovo.', hint: 'Impostazioni, scorri fino in fondo, Esci.' },
    T04: { title: 'Crea il tuo secondo profilo.', hint: 'Tocca la tua foto profilo in alto, poi "Aggiungi profilo". Scegli il secondo ruolo che ti è stato assegnato.' },
    T05: { title: 'Completa il profilo: bio, generi, città e almeno due link.', hint: 'Profilo, poi Modifica.' },
    T06: { title: 'Carica una foto profilo.', hint: 'Profilo, Modifica, tocca la foto.' },
    T07: { title: 'Segna le tue date disponibili per i prossimi due mesi.', hint: 'Profilo > Gestisci > Calendario. Tocca i giorni in cui sei libero.' },
    T08: { title: 'Aggiorna il tuo programma di viaggio.', hint: 'Profilo > Gestisci > Programma di viaggio. Aggiungi una città e le date in cui ci sarai.' },
    T09: { title: 'Cambia la lingua dell\'app, poi rimetti quella che preferisci.', hint: 'Impostazioni > Lingua.' },
    T10: { title: 'Verifica il tuo account Instagram.', hint: 'Profilo, tocca il banner "non verificato", copia il codice e invialo in DM a @tora.verify.' },
    T11: { title: 'Apri il globo in Search e tocca una città per vedere chi c\'è.', hint: 'Tab Search, vista Globo. I pin mostrano dove sono i membri: toccane uno per aprire quella città. Funziona anche il filtro città nella vista elenco.' },
    T12: { title: 'Metti "mi piace" a un altro profilo.', hint: 'Tocca il cuore su una scheda profilo.' },
    T13: { title: 'Invia una richiesta di connessione al contatto che ti è stato assegnato.', hint: 'Apri il suo profilo, tocca Connetti, scrivi un breve messaggio.' },
    T14: { title: 'Invia un messaggio a una connessione.', hint: 'Tab Messaggi, oppure il pulsante messaggio sul suo profilo.' },
    T15: { title: 'Invia un file in una chat. Va bene qualsiasi allegato.', hint: 'La graffetta nella barra della chat.' },
    T16: { title: 'Invia un\'offerta al contatto che ti è stato assegnato.', hint: 'Apri il suo profilo o la chat con lui, poi "Fai un\'offerta".' },
    T17: { title: 'Invia un\'offerta con una scadenza per l\'acconto e una per il saldo.', hint: 'I due campi data in fondo al modulo dell\'offerta.' },
    T18: { title: 'Apri l\'offerta che ti aspetta e leggi i termini.', hint: 'Tab Prenotazioni. È in cima.' },
    T19: { title: 'Fai una controproposta cambiando il cachet e almeno un altro termine.', hint: 'Apri l\'offerta, tocca Controproposta.' },
    T20: { title: 'Accetta un\'offerta.', hint: 'Rivedi offerta, poi Accetta.' },
    T21: { title: 'Rifiuta un\'offerta e scrivi il motivo.', hint: 'Rivedi offerta, poi Rifiuta.' },
    T22: { title: 'Invia un contratto per un accordo concluso. Va bene qualsiasi allegato.', hint: 'Apri la prenotazione accettata, tocca Invia contratto, carica un file qualsiasi.' },
    T23: { title: 'Firma un contratto che ti è stato inviato.', hint: 'Apri la prenotazione, tocca Firma.' },
    T24: { title: 'Salta il passaggio del contratto, poi ripristinalo.', hint: '"Salta contratto" sulla scheda prenotazione, poi "Ripristina passaggio contratto".' },
    T25: { title: 'Segna un acconto come inviato e allega una ricevuta. Va bene un\'immagine o un PDF.', hint: 'Passaggio Pagamento sulla scheda prenotazione.' },
    T26: { title: 'Conferma di aver ricevuto il pagamento.', hint: 'Passaggio Pagamento sulla scheda prenotazione.' },
    T27: { title: 'Porta una prenotazione fino in fondo: dal primo messaggio a confermata e pagata.', hint: 'Qui non ci sono scorciatoie. È tutto il prodotto.' },
    T28: { title: 'Accetta l\'agente che ha chiesto di rappresentarti.', hint: 'Notifiche, oppure la chat con quell\'agente.' },
    T29: { title: 'Carica il tuo press kit e il tuo rider tecnico. Va bene qualsiasi file.', hint: 'Graffetta della chat, oppure il passaggio Documenti dentro una prenotazione.' },
    T30: { title: 'Aggiungi tre artisti al tuo roster.', hint: 'Profilo > Artisti rappresentati > Aggiungi. Cerca su TORA o inseriscili a mano.' },
    T31: { title: 'Invia una richiesta di rappresentanza a un artista su TORA.', hint: 'Il suo profilo, "Richiedi rappresentanza".' },
    T32: { title: 'Apri Gestisci artista e completa una voce della lista azioni.', hint: 'Roster, tocca Gestisci su un artista. La lista è in cima.' },
    T33: { title: 'Negozia una prenotazione per conto di un artista che rappresenti, non a nome tuo.', hint: 'Quando rispondi, passa il contesto dell\'offerta all\'artista.' },
    T34: { title: 'Proponi uno dei tuoi artisti a un locale via messaggio. I locali non ricevono offerte, le inviano.', hint: 'Apri il profilo del locale e tocca "Invia una proposta". Se è interessato ti manderà un\'offerta.' },
    T35: { title: 'Rispondi a una proposta arrivata via messaggio inviando un\'offerta.', hint: 'Apri la chat, poi "Fai un\'offerta" da quella conversazione.' },
    T36: { title: 'Apri un tour in Tour Kickstart e tocca "Mi interessa".', hint: 'Tab Tour > Tour Kickstart. Un tocco: l\'artista vede l\'interesse crescere città per città. Mettere "mi piace" a un artista in tour attiva anche un avviso viaggio per te.' },
    T37: { title: 'Proponi una data sul tour di qualcuno.', hint: 'Esplora > Tour, apri un tour, "Proponi data".' },
    T39: { title: 'Imposta la capienza e i dettagli del tuo locale.', hint: 'Profilo > Modifica. Capienza, città, generi, foto.' },
    T40: { title: 'Condividi le specifiche tecniche e le info di ospitalità con un artista. Va bene qualsiasi file.', hint: 'Graffetta della chat, oppure il passaggio Documenti in una prenotazione.' },
    T41: { title: 'Pubblica qualcosa in News.', hint: 'Tab News, l\'editor è in cima.' },
    T42: { title: 'Metti "mi piace" o commenta il post di qualcun altro.', hint: 'Il cuore o l\'icona commento su un post.' },
    T43: { title: 'Attiva le notifiche, poi verifica che una ti arrivi.', hint: 'La scheda che compare dopo il login, oppure Impostazioni > Notifiche. Su iPhone devi prima aggiungere TORA alla schermata Home (attività T01).' },
    T45: { title: 'Passa a Premium con la carta di test 4242 4242 4242 4242, scadenza futura qualsiasi, CVC qualsiasi.', hint: 'Impostazioni > Premium, oppure l\'avviso che compare quando raggiungi un limite.' },
    T46: { title: 'Annulla l\'abbonamento, poi controlla cosa dice l\'app sulla data di fine accesso.', hint: 'Impostazioni > Gestisci abbonamento > Annulla.' },
    'T07@AGENT': { title: 'Segna le date disponibili di uno dei tuoi artisti per i prossimi due mesi.', hint: 'Profilo > Gestisci > scegli l\'artista > Calendario. Tocca i giorni in cui è libero.' },
    'T08@AGENT': { title: 'Aggiorna il programma di viaggio di uno dei tuoi artisti.', hint: 'Profilo > Gestisci > scegli l\'artista > Programma di viaggio. Aggiungi una città e le date.' },
    T51: { title: 'Verifica finale: il mese prossimo gestiresti una prenotazione vera su TORA? Sì o no, e perché.', hint: 'Tocca Rispondi. Basta una frase.' },
  },
  es: {
    T01: { title: 'Añade TORA a la pantalla de inicio de tu teléfono.', hint: 'iPhone: abre beta.torahub.io en Safari, toca el icono de compartir y luego "Añadir a pantalla de inicio". Android y ordenador: toca el icono de instalar en la barra de direcciones.' },
    T02: { title: 'Inicia sesión con el código de invitación de tu email.', hint: 'Abre el email, toca el botón, pega el código y elige una contraseña.' },
    T03: { title: 'Cierra sesión y vuelve a entrar.', hint: 'Ajustes, baja hasta el final, Cerrar sesión.' },
    T04: { title: 'Crea tu segundo perfil.', hint: 'Toca tu foto de perfil arriba y luego "Añadir perfil". Elige el segundo rol que te asignaron.' },
    T05: { title: 'Completa tu perfil: bio, géneros, ciudad y al menos dos enlaces.', hint: 'Perfil, luego Editar.' },
    T06: { title: 'Sube una foto de perfil.', hint: 'Perfil, Editar, toca la foto.' },
    T07: { title: 'Marca tus fechas disponibles para los próximos dos meses.', hint: 'Perfil > Gestionar > Calendario. Toca los días en que estás libre.' },
    T08: { title: 'Actualiza tu calendario de viajes.', hint: 'Perfil > Gestionar > Calendario de viajes. Añade una ciudad y las fechas en que estarás allí.' },
    T09: { title: 'Cambia el idioma de la app y vuelve al que prefieras.', hint: 'Ajustes > Idioma.' },
    T10: { title: 'Verifica tu cuenta de Instagram.', hint: 'Perfil, toca el aviso "sin verificar", copia el código y envíalo por DM a @tora.verify.' },
    T11: { title: 'Abre el globo en Search y toca una ciudad para ver quién está allí.', hint: 'Pestaña Search, vista Globo. Los pines muestran dónde hay miembros: toca uno para abrir esa ciudad. El filtro de ciudad en la vista de lista también sirve.' },
    T12: { title: 'Dale "me gusta" a otro perfil.', hint: 'Toca el corazón en una tarjeta de perfil.' },
    T13: { title: 'Envía una solicitud de conexión a tu contacto asignado.', hint: 'Abre su perfil, toca Conectar y escribe un mensaje corto.' },
    T14: { title: 'Envía un mensaje a una conexión.', hint: 'Pestaña Mensajes, o el botón de mensaje en su perfil.' },
    T15: { title: 'Envía un archivo en un chat. Vale cualquier adjunto.', hint: 'El clip en la barra del chat.' },
    T16: { title: 'Envía una oferta a tu contacto asignado.', hint: 'Abre su perfil o tu chat con él y luego "Hacer una oferta".' },
    T17: { title: 'Envía una oferta que incluya una fecha límite para el depósito y otra para el pago final.', hint: 'Los dos campos de fecha al final del formulario de oferta.' },
    T18: { title: 'Abre la oferta que te espera y lee las condiciones.', hint: 'Pestaña Reservas. Está arriba del todo.' },
    T19: { title: 'Haz una contraoferta cambiando el caché y al menos otra condición.', hint: 'Abre la oferta, toca Contraoferta.' },
    T20: { title: 'Acepta una oferta.', hint: 'Revisar oferta, luego Aceptar.' },
    T21: { title: 'Rechaza una oferta y escribe el motivo.', hint: 'Revisar oferta, luego Rechazar.' },
    T22: { title: 'Envía un contrato de un acuerdo cerrado. Vale cualquier adjunto.', hint: 'Abre la reserva aceptada, toca Enviar contrato y sube cualquier archivo.' },
    T23: { title: 'Firma un contrato que te hayan enviado.', hint: 'Abre la reserva, toca Firmar.' },
    T24: { title: 'Omite el paso del contrato y luego restáuralo.', hint: '"Omitir contrato" en la tarjeta de la reserva, luego "Restaurar paso del contrato".' },
    T25: { title: 'Marca un depósito como enviado y adjunta un recibo. Vale una imagen o un PDF.', hint: 'Paso Pago en la tarjeta de la reserva.' },
    T26: { title: 'Confirma que recibiste el pago.', hint: 'Paso Pago en la tarjeta de la reserva.' },
    T27: { title: 'Lleva una reserva hasta el final: del primer mensaje a confirmada y pagada.', hint: 'Aquí no hay atajo. Es el producto entero.' },
    T28: { title: 'Acepta al agente que pidió representarte.', hint: 'Notificaciones, o el chat con ese agente.' },
    T29: { title: 'Sube tu press kit y tu rider técnico. Vale cualquier archivo.', hint: 'Clip del chat, o el paso Documentos dentro de una reserva.' },
    T30: { title: 'Añade tres artistas a tu roster.', hint: 'Perfil > Artistas representados > Añadir. Busca en TORA o escríbelos a mano.' },
    T31: { title: 'Envía una solicitud de representación a un artista de TORA.', hint: 'Su perfil, "Solicitar representación".' },
    T32: { title: 'Abre Gestionar artista y resuelve un punto de la lista de acciones.', hint: 'Roster, toca Gestionar en un artista. La lista está arriba.' },
    T33: { title: 'Negocia una reserva en nombre de un artista que representas, no como tú mismo.', hint: 'Al responder, cambia el contexto de la oferta al artista.' },
    T34: { title: 'Propón uno de tus artistas a un local por mensaje. Los locales no reciben ofertas, las envían.', hint: 'Abre el perfil del local y toca "Enviar propuesta". Si le interesa, te enviará una oferta.' },
    T35: { title: 'Responde a una propuesta recibida por mensaje enviando una oferta.', hint: 'Abre el chat y luego "Hacer una oferta" desde esa conversación.' },
    T36: { title: 'Abre una gira en Tour Kickstart y toca "Me interesa".', hint: 'Pestaña Tour > Tour Kickstart. Un toque: el artista ve crecer el interés ciudad por ciudad. Dar "me gusta" a un artista de gira también activa una alerta de viaje para ti.' },
    T37: { title: 'Propón una fecha en la gira de alguien.', hint: 'Explorar > Giras, abre una gira, "Proponer fecha".' },
    T39: { title: 'Define tu aforo y los datos de tu local.', hint: 'Perfil > Editar. Aforo, ciudad, géneros, fotos.' },
    T40: { title: 'Comparte tus especificaciones técnicas y la info de hospitalidad con un artista. Vale cualquier archivo.', hint: 'Clip del chat, o el paso Documentos en una reserva.' },
    T41: { title: 'Publica algo en News.', hint: 'Pestaña News, el editor está arriba.' },
    T42: { title: 'Dale "me gusta" o comenta la publicación de otra persona.', hint: 'El corazón o el icono de comentario en cualquier publicación.' },
    T43: { title: 'Activa las notificaciones y confirma que te llega una.', hint: 'La tarjeta que aparece tras iniciar sesión, o Ajustes > Notificaciones. En iPhone primero debes añadir TORA a la pantalla de inicio (tarea T01).' },
    T45: { title: 'Pásate a Premium con la tarjeta de prueba 4242 4242 4242 4242, cualquier caducidad futura y cualquier CVC.', hint: 'Ajustes > Premium, o el aviso que aparece al llegar a un límite.' },
    T46: { title: 'Cancela tu suscripción y comprueba qué te dice la app sobre la fecha en que termina tu acceso.', hint: 'Ajustes > Gestionar suscripción > Cancelar.' },
    'T07@AGENT': { title: 'Marca las fechas disponibles de uno de tus artistas para los próximos dos meses.', hint: 'Perfil > Gestionar > elige tu artista > Calendario. Toca los días en que está libre.' },
    'T08@AGENT': { title: 'Actualiza el calendario de viajes de uno de tus artistas.', hint: 'Perfil > Gestionar > elige tu artista > Calendario de viajes. Añade una ciudad y las fechas.' },
    T51: { title: 'Pregunta final: ¿harías una reserva real a través de TORA el mes que viene? Sí o no, y por qué.', hint: 'Toca Responder. Con una frase basta.' },
  },
  fr: {
    T01: { title: 'Ajoute TORA à l\'écran d\'accueil de ton téléphone.', hint: 'iPhone : ouvre beta.torahub.io dans Safari, touche l\'icône de partage puis « Sur l\'écran d\'accueil ». Android et ordinateur : touche l\'icône d\'installation dans la barre d\'adresse.' },
    T02: { title: 'Connecte-toi avec le code d\'invitation reçu par email.', hint: 'Ouvre l\'email, touche le bouton, colle le code, choisis un mot de passe.' },
    T03: { title: 'Déconnecte-toi, puis reconnecte-toi.', hint: 'Réglages, tout en bas, Se déconnecter.' },
    T04: { title: 'Crée ton second profil.', hint: 'Touche ta photo de profil en haut, puis « Ajouter un profil ». Choisis le second rôle qui t\'a été attribué.' },
    T05: { title: 'Complète ton profil : bio, genres, ville et au moins deux liens.', hint: 'Profil, puis Modifier.' },
    T06: { title: 'Ajoute une photo de profil.', hint: 'Profil, Modifier, touche la photo.' },
    T07: { title: 'Indique tes dates disponibles pour les deux prochains mois.', hint: 'Profil > Gérer > Calendrier. Touche les jours où tu es libre.' },
    T08: { title: 'Mets à jour ton planning de déplacements.', hint: 'Profil > Gérer > Planning de déplacements. Ajoute une ville et les dates où tu y seras.' },
    T09: { title: 'Change la langue de l\'app, puis remets celle que tu préfères.', hint: 'Réglages > Langue.' },
    T10: { title: 'Vérifie ton compte Instagram.', hint: 'Profil, touche le bandeau « non vérifié », copie le code et envoie-le en DM à @tora.verify.' },
    T11: { title: 'Ouvre le globe dans Search et touche une ville pour voir qui s\'y trouve.', hint: 'Onglet Search, vue Globe. Les épingles montrent où sont les membres : touche-en une pour ouvrir la ville. Le filtre par ville de la vue liste marche aussi.' },
    T12: { title: 'Aime un autre profil.', hint: 'Touche le cœur sur une carte de profil.' },
    T13: { title: 'Envoie une demande de connexion au contact qui t\'a été attribué.', hint: 'Ouvre son profil, touche Se connecter, écris un court message.' },
    T14: { title: 'Envoie un message à une connexion.', hint: 'Onglet Messages, ou le bouton message sur son profil.' },
    T15: { title: 'Envoie un fichier dans une discussion. N\'importe quelle pièce jointe convient.', hint: 'Le trombone dans la barre de discussion.' },
    T16: { title: 'Envoie une offre au contact qui t\'a été attribué.', hint: 'Ouvre son profil ou ta discussion avec lui, puis « Faire une offre ».' },
    T17: { title: 'Envoie une offre avec une date limite d\'acompte et une date limite de paiement final.', hint: 'Les deux champs de date en bas du formulaire d\'offre.' },
    T18: { title: 'Ouvre l\'offre qui t\'attend et lis les conditions.', hint: 'Onglet Réservations. Elle est tout en haut.' },
    T19: { title: 'Fais une contre-offre en changeant le cachet et au moins une autre condition.', hint: 'Ouvre l\'offre, touche Contre-offre.' },
    T20: { title: 'Accepte une offre.', hint: 'Examiner l\'offre, puis Accepter.' },
    T21: { title: 'Refuse une offre et écris la raison.', hint: 'Examiner l\'offre, puis Refuser.' },
    T22: { title: 'Envoie un contrat pour un accord conclu. N\'importe quelle pièce jointe convient.', hint: 'Ouvre la réservation acceptée, touche Envoyer le contrat, télécharge n\'importe quel fichier.' },
    T23: { title: 'Signe un contrat qu\'on t\'a envoyé.', hint: 'Ouvre la réservation, touche Signer.' },
    T24: { title: 'Passe l\'étape du contrat, puis rétablis-la.', hint: '« Passer le contrat » sur la carte de réservation, puis « Rétablir l\'étape contrat ».' },
    T25: { title: 'Marque un acompte comme envoyé et joins un reçu. Une image ou un PDF convient.', hint: 'Étape Paiement sur la carte de réservation.' },
    T26: { title: 'Confirme que tu as reçu le paiement.', hint: 'Étape Paiement sur la carte de réservation.' },
    T27: { title: 'Mène une réservation jusqu\'au bout : du premier message à confirmée et payée.', hint: 'Pas de raccourci ici. C\'est tout le produit.' },
    T28: { title: 'Accepte l\'agent qui a demandé à te représenter.', hint: 'Notifications, ou la discussion avec cet agent.' },
    T29: { title: 'Télécharge ton press kit et ta fiche technique. N\'importe quel fichier convient.', hint: 'Trombone de la discussion, ou l\'étape Documents dans une réservation.' },
    T30: { title: 'Ajoute trois artistes à ton roster.', hint: 'Profil > Artistes représentés > Ajouter. Cherche sur TORA ou saisis-les à la main.' },
    T31: { title: 'Envoie une demande de représentation à un artiste sur TORA.', hint: 'Son profil, « Demander la représentation ».' },
    T32: { title: 'Ouvre Gérer l\'artiste et traite un point de la liste d\'actions.', hint: 'Roster, touche Gérer sur un artiste. La liste est en haut.' },
    T33: { title: 'Négocie une réservation au nom d\'un artiste que tu représentes, pas en ton nom.', hint: 'En répondant, bascule le contexte de l\'offre vers l\'artiste.' },
    T34: { title: 'Propose un de tes artistes à une salle par message. Les salles ne reçoivent pas d\'offres, elles en envoient.', hint: 'Ouvre le profil de la salle et touche « Envoyer une proposition ». Si elle est intéressée, elle t\'enverra une offre.' },
    T35: { title: 'Réponds à une proposition reçue par message en envoyant une offre.', hint: 'Ouvre la discussion, puis « Faire une offre » depuis cette conversation.' },
    T36: { title: 'Ouvre une tournée dans Tour Kickstart et touche « Ça m\'intéresse ».', hint: 'Onglet Tour > Tour Kickstart. Un seul geste : l\'artiste voit l\'intérêt monter ville par ville. Aimer un artiste en tournée crée aussi une alerte déplacement pour toi.' },
    T37: { title: 'Propose une date sur la tournée de quelqu\'un.', hint: 'Explorer > Tournées, ouvre une tournée, « Proposer une date ».' },
    T39: { title: 'Renseigne ta capacité et les infos de ta salle.', hint: 'Profil > Modifier. Capacité, ville, genres, photos.' },
    T40: { title: 'Partage ta fiche technique et les infos d\'accueil avec un artiste. N\'importe quel fichier convient.', hint: 'Trombone de la discussion, ou l\'étape Documents dans une réservation.' },
    T41: { title: 'Publie quelque chose dans News.', hint: 'Onglet News, l\'éditeur est en haut.' },
    T42: { title: 'Aime ou commente la publication de quelqu\'un d\'autre.', hint: 'Le cœur ou l\'icône commentaire sur n\'importe quelle publication.' },
    T43: { title: 'Active les notifications, puis vérifie qu\'une te parvient.', hint: 'La carte qui apparaît après la connexion, ou Réglages > Notifications. Sur iPhone, il faut d\'abord ajouter TORA à l\'écran d\'accueil (tâche T01).' },
    T45: { title: 'Passe à Premium avec la carte de test 4242 4242 4242 4242, n\'importe quelle date future, n\'importe quel CVC.', hint: 'Réglages > Premium, ou l\'invite qui apparaît quand tu atteins une limite.' },
    T46: { title: 'Annule ton abonnement, puis vérifie ce que l\'app t\'indique sur la date de fin d\'accès.', hint: 'Réglages > Gérer l\'abonnement > Annuler.' },
    'T07@AGENT': { title: 'Indique les dates disponibles d\'un de tes artistes pour les deux prochains mois.', hint: 'Profil > Gérer > choisis ton artiste > Calendrier. Touche les jours où il est libre.' },
    'T08@AGENT': { title: 'Mets à jour le planning de déplacements d\'un de tes artistes.', hint: 'Profil > Gérer > choisis ton artiste > Planning de déplacements. Ajoute une ville et les dates.' },
    T51: { title: 'Dernière question : ferais-tu une vraie réservation via TORA le mois prochain ? Oui ou non, et pourquoi.', hint: 'Touche Répondre. Une phrase suffit.' },
  },
  pt: {
    T01: { title: 'Adiciona o TORA ao ecrã inicial do teu telemóvel.', hint: 'iPhone: abre beta.torahub.io no Safari, toca no ícone de partilha e depois em "Adicionar ao ecrã principal". Android e computador: toca no ícone de instalar na barra de endereço.' },
    T02: { title: 'Inicia sessão com o código de convite do teu email.', hint: 'Abre o email, toca no botão, cola o código e escolhe uma palavra-passe.' },
    T03: { title: 'Termina a sessão e volta a entrar.', hint: 'Definições, desce até ao fim, Terminar sessão.' },
    T04: { title: 'Cria o teu segundo perfil.', hint: 'Toca na tua foto de perfil no topo e depois em "Adicionar perfil". Escolhe o segundo papel que te foi atribuído.' },
    T05: { title: 'Completa o teu perfil: bio, géneros, cidade e pelo menos dois links.', hint: 'Perfil, depois Editar.' },
    T06: { title: 'Carrega uma foto de perfil.', hint: 'Perfil, Editar, toca na foto.' },
    T07: { title: 'Marca as tuas datas disponíveis para os próximos dois meses.', hint: 'Perfil > Gerir > Calendário. Toca nos dias em que estás livre.' },
    T08: { title: 'Atualiza o teu calendário de viagens.', hint: 'Perfil > Gerir > Calendário de viagens. Adiciona uma cidade e as datas em que lá estarás.' },
    T09: { title: 'Muda o idioma da app e depois volta ao que preferes.', hint: 'Definições > Idioma.' },
    T10: { title: 'Verifica a tua conta de Instagram.', hint: 'Perfil, toca no aviso "não verificado", copia o código e envia-o por DM para @tora.verify.' },
    T11: { title: 'Abre o globo em Search e toca numa cidade para ver quem lá está.', hint: 'Separador Search, vista Globo. Os pinos mostram onde há membros: toca num para abrir essa cidade. O filtro de cidade na vista de lista também funciona.' },
    T12: { title: 'Dá "gosto" a outro perfil.', hint: 'Toca no coração num cartão de perfil.' },
    T13: { title: 'Envia um pedido de ligação ao contacto que te foi atribuído.', hint: 'Abre o perfil dele, toca em Ligar e escreve uma mensagem curta.' },
    T14: { title: 'Envia uma mensagem a uma ligação.', hint: 'Separador Mensagens, ou o botão de mensagem no perfil.' },
    T15: { title: 'Envia um ficheiro numa conversa. Serve qualquer anexo.', hint: 'O clipe na barra da conversa.' },
    T16: { title: 'Envia uma oferta ao contacto que te foi atribuído.', hint: 'Abre o perfil dele ou a vossa conversa e depois "Fazer uma oferta".' },
    T17: { title: 'Envia uma oferta com um prazo para o depósito e outro para o pagamento final.', hint: 'Os dois campos de data no fundo do formulário da oferta.' },
    T18: { title: 'Abre a oferta que te espera e lê as condições.', hint: 'Separador Reservas. Está no topo.' },
    T19: { title: 'Faz uma contraproposta alterando o cachê e pelo menos outra condição.', hint: 'Abre a oferta, toca em Contraproposta.' },
    T20: { title: 'Aceita uma oferta.', hint: 'Rever oferta, depois Aceitar.' },
    T21: { title: 'Recusa uma oferta e escreve o motivo.', hint: 'Rever oferta, depois Recusar.' },
    T22: { title: 'Envia um contrato de um acordo fechado. Serve qualquer anexo.', hint: 'Abre a reserva aceite, toca em Enviar contrato e carrega qualquer ficheiro.' },
    T23: { title: 'Assina um contrato que te enviaram.', hint: 'Abre a reserva, toca em Assinar.' },
    T24: { title: 'Salta o passo do contrato e depois repõe-no.', hint: '"Saltar contrato" no cartão da reserva, depois "Repor passo do contrato".' },
    T25: { title: 'Marca um depósito como enviado e anexa um recibo. Serve uma imagem ou um PDF.', hint: 'Passo Pagamento no cartão da reserva.' },
    T26: { title: 'Confirma que recebeste o pagamento.', hint: 'Passo Pagamento no cartão da reserva.' },
    T27: { title: 'Leva uma reserva até ao fim: da primeira mensagem até confirmada e paga.', hint: 'Aqui não há atalho. É o produto inteiro.' },
    T28: { title: 'Aceita o agente que pediu para te representar.', hint: 'Notificações, ou a conversa com esse agente.' },
    T29: { title: 'Carrega o teu press kit e o teu rider técnico. Serve qualquer ficheiro.', hint: 'Clipe da conversa, ou o passo Documentos dentro de uma reserva.' },
    T30: { title: 'Adiciona três artistas ao teu roster.', hint: 'Perfil > Artistas representados > Adicionar. Pesquisa no TORA ou escreve-os à mão.' },
    T31: { title: 'Envia um pedido de representação a um artista no TORA.', hint: 'O perfil dele, "Pedir representação".' },
    T32: { title: 'Abre Gerir artista e resolve um item da lista de ações.', hint: 'Roster, toca em Gerir num artista. A lista está no topo.' },
    T33: { title: 'Negocia uma reserva em nome de um artista que representas, não como tu próprio.', hint: 'Ao responder, muda o contexto da oferta para o artista.' },
    T34: { title: 'Propõe um dos teus artistas a um espaço por mensagem. Os espaços não recebem ofertas, enviam-nas.', hint: 'Abre o perfil do espaço e toca em "Enviar proposta". Se houver interesse, enviam-te uma oferta.' },
    T35: { title: 'Responde a uma proposta recebida por mensagem enviando uma oferta.', hint: 'Abre a conversa e depois "Fazer uma oferta" a partir dessa conversa.' },
    T36: { title: 'Abre uma digressão em Tour Kickstart e toca em "Tenho interesse".', hint: 'Separador Tour > Tour Kickstart. Um toque: o artista vê o interesse crescer cidade a cidade. Dar "gosto" a um artista em digressão também cria um alerta de viagem para ti.' },
    T37: { title: 'Propõe uma data na digressão de alguém.', hint: 'Explorar > Digressões, abre uma digressão, "Propor data".' },
    T39: { title: 'Define a tua lotação e os dados do teu espaço.', hint: 'Perfil > Editar. Lotação, cidade, géneros, fotos.' },
    T40: { title: 'Partilha as tuas especificações técnicas e a informação de hospitalidade com um artista. Serve qualquer ficheiro.', hint: 'Clipe da conversa, ou o passo Documentos numa reserva.' },
    T41: { title: 'Publica algo em News.', hint: 'Separador News, o editor está no topo.' },
    T42: { title: 'Dá "gosto" ou comenta a publicação de outra pessoa.', hint: 'O coração ou o ícone de comentário em qualquer publicação.' },
    T43: { title: 'Ativa as notificações e confirma que recebes uma.', hint: 'O cartão que aparece depois de entrares, ou Definições > Notificações. No iPhone tens primeiro de adicionar o TORA ao ecrã inicial (tarefa T01).' },
    T45: { title: 'Passa a Premium com o cartão de teste 4242 4242 4242 4242, qualquer validade futura, qualquer CVC.', hint: 'Definições > Premium, ou o aviso que aparece quando atinges um limite.' },
    T46: { title: 'Cancela a tua subscrição e vê o que a app te diz sobre a data em que o acesso termina.', hint: 'Definições > Gerir subscrição > Cancelar.' },
    'T07@AGENT': { title: 'Marca as datas disponíveis de um dos teus artistas para os próximos dois meses.', hint: 'Perfil > Gerir > escolhe o artista > Calendário. Toca nos dias em que está livre.' },
    'T08@AGENT': { title: 'Atualiza o calendário de viagens de um dos teus artistas.', hint: 'Perfil > Gerir > escolhe o artista > Calendário de viagens. Adiciona uma cidade e as datas.' },
    T51: { title: 'Pergunta final: farias uma reserva real através do TORA no próximo mês? Sim ou não, e porquê.', hint: 'Toca em Responder. Uma frase chega.' },
  },
  zh: {
    T01: { title: '把 TORA 添加到手机主屏幕。', hint: 'iPhone：在 Safari 打开 beta.torahub.io，点分享图标，再点"添加到主屏幕"。Android 和电脑：点地址栏里的安装图标。' },
    T02: { title: '用邮件里的邀请码登录。', hint: '打开邮件，点按钮，粘贴邀请码，设置密码。' },
    T03: { title: '退出登录，再重新登录。', hint: '设置，滑到底部，退出登录。' },
    T04: { title: '创建你的第二个档案。', hint: '点顶部的头像，再点"添加档案"。选择分配给你的第二个角色。' },
    T05: { title: '完善档案：简介、曲风、城市，以及至少两个链接。', hint: '档案 → 编辑。' },
    T06: { title: '上传一张头像。', hint: '档案 → 编辑 → 点头像。' },
    T07: { title: '标记未来两个月的空档日期。', hint: '档案 > 管理 > 日历。点选你有空的日期。' },
    T08: { title: '更新你的行程安排。', hint: '档案 > 管理 > 行程安排。添加城市和你在那里的日期。' },
    T09: { title: '切换应用语言，再切回你习惯的语言。', hint: '设置 > 语言。' },
    T10: { title: '验证你的 Instagram 账号。', hint: '档案页点"未验证"横幅，复制验证码，私信发给 @tora.verify。' },
    T11: { title: '在 Search 打开地球视图，点一个城市看看谁在那里。', hint: 'Search 标签页，地球视图。图钉表示成员所在城市，点一下即可打开。列表视图里的城市筛选也可以。' },
    T12: { title: '给另一个档案点赞。', hint: '点档案卡片上的爱心。' },
    T13: { title: '向分配给你的联系人发送连接请求。', hint: '打开对方档案，点"连接"，写一句简短的话。' },
    T14: { title: '给一位已连接的成员发消息。', hint: '消息标签页，或对方档案上的消息按钮。' },
    T15: { title: '在聊天里发一个文件。任何附件都可以。', hint: '聊天栏里的回形针。' },
    T16: { title: '向分配给你的联系人发送报价。', hint: '打开对方档案或你们的聊天，再点"发出报价"。' },
    T17: { title: '发送一份包含定金截止日和尾款截止日的报价。', hint: '报价表单底部的两个日期栏。' },
    T18: { title: '打开等你处理的报价，阅读条款。', hint: '预订标签页，就在最上面。' },
    T19: { title: '对报价还价：修改费用和至少一项其他条款。', hint: '打开报价，点"还价"。' },
    T20: { title: '接受一份报价。', hint: '查看报价，然后接受。' },
    T21: { title: '拒绝一份报价并写明原因。', hint: '查看报价，然后拒绝。' },
    T22: { title: '为已达成的交易发送合同。任何附件都可以。', hint: '打开已接受的预订，点"发送合同"，上传任意文件。' },
    T23: { title: '签署别人发给你的合同。', hint: '打开预订，点"签署"。' },
    T24: { title: '跳过合同步骤，然后再恢复它。', hint: '预订卡片上的"跳过合同"，再点"恢复合同步骤"。' },
    T25: { title: '把定金标记为已付并附上凭证。图片或 PDF 都可以。', hint: '预订卡片上的付款步骤。' },
    T26: { title: '确认你已收到付款。', hint: '预订卡片上的付款步骤。' },
    T27: { title: '把一次预订从头走到尾：从第一条消息到确认并付款完成。', hint: '这一项没有捷径，它就是整个产品。' },
    T28: { title: '接受申请代理你的经纪人。', hint: '通知，或与该经纪人的聊天。' },
    T29: { title: '上传你的宣传资料和技术需求单。任何文件都可以。', hint: '聊天里的回形针，或预订里的文件步骤。' },
    T30: { title: '把三位艺人加入你的名册。', hint: '档案 > 代理艺人 > 添加。在 TORA 搜索或手动输入。' },
    T31: { title: '向 TORA 上的一位艺人发送代理申请。', hint: '对方档案，"申请代理"。' },
    T32: { title: '打开"管理艺人"，处理待办列表里的一项。', hint: '名册，点某位艺人的"管理"。列表在顶部。' },
    T33: { title: '以你代理的艺人的名义（而不是你自己）谈一次预订。', hint: '回复时把报价主体切换为该艺人。' },
    T34: { title: '通过消息向场地推荐你的一位艺人。场地不接收报价，只发出报价。', hint: '打开场地档案，点"发送推荐"。如果对方有兴趣，会给你发报价。' },
    T35: { title: '用一份报价回复通过消息收到的推荐。', hint: '打开聊天，在该对话里点"发出报价"。' },
    T36: { title: '在 Tour Kickstart 打开一个巡演，点"我有兴趣"。', hint: 'Tour 标签页 > Tour Kickstart。一键表达兴趣，艺人能看到各城市的热度。给巡演中的艺人点赞还会自动为你设置行程提醒。' },
    T37: { title: '在别人的巡演里提议一个日期。', hint: '探索 > 巡演，打开一个巡演，"提议日期"。' },
    T39: { title: '设置你的容纳人数和场地信息。', hint: '档案 > 编辑。容纳人数、城市、曲风、照片。' },
    T40: { title: '把技术规格和接待信息分享给一位艺人。任何文件都可以。', hint: '聊天里的回形针，或预订里的文件步骤。' },
    T41: { title: '在 News 发一条动态。', hint: 'News 标签页，顶部的编辑框。' },
    T42: { title: '给别人的动态点赞或评论。', hint: '任意动态上的爱心或评论图标。' },
    T43: { title: '开启通知，并确认能收到一条。', hint: '登录后出现的卡片，或设置 > 通知。iPhone 需要先把 TORA 添加到主屏幕（任务 T01）。' },
    T45: { title: '用测试卡 4242 4242 4242 4242 升级到 Premium，有效期任意未来日期，CVC 任意。', hint: '设置 > Premium，或达到上限时出现的提示。' },
    T46: { title: '取消订阅，然后看看应用对访问截止日期的说明。', hint: '设置 > 管理订阅 > 取消。' },
    'T07@AGENT': { title: '为你的一位艺人标记未来两个月的空档日期。', hint: '档案 > 管理 > 选择艺人 > 日历。点选对方有空的日期。' },
    'T08@AGENT': { title: '更新你的一位艺人的行程安排。', hint: '档案 > 管理 > 选择艺人 > 行程安排。添加城市和日期。' },
    T51: { title: '最后一问：下个月你会用 TORA 做一次真实的预订吗？是或否，以及原因。', hint: '点"回答"。一句话就够。' },
  },
  ko: {
    T01: { title: 'TORA를 휴대폰 홈 화면에 추가하세요.', hint: 'iPhone: Safari에서 beta.torahub.io를 열고 공유 아이콘 → "홈 화면에 추가". Android·PC: 주소창의 설치 아이콘을 누르세요.' },
    T02: { title: '이메일의 초대 코드로 로그인하세요.', hint: '이메일을 열고 버튼을 누른 뒤 코드를 붙여넣고 비밀번호를 설정하세요.' },
    T03: { title: '로그아웃한 뒤 다시 로그인하세요.', hint: '설정, 맨 아래로 스크롤, 로그아웃.' },
    T04: { title: '두 번째 프로필을 만드세요.', hint: '상단의 프로필 사진을 누르고 "프로필 추가". 배정받은 두 번째 역할을 선택하세요.' },
    T05: { title: '프로필을 완성하세요: 소개, 장르, 도시, 링크 2개 이상.', hint: '프로필 → 편집.' },
    T06: { title: '프로필 사진을 올리세요.', hint: '프로필 → 편집 → 사진을 누르세요.' },
    T07: { title: '앞으로 두 달간 가능한 날짜를 표시하세요.', hint: '프로필 > 관리 > 캘린더. 비어 있는 날짜를 누르세요.' },
    T08: { title: '이동 일정을 업데이트하세요.', hint: '프로필 > 관리 > 이동 일정. 도시와 머무는 날짜를 추가하세요.' },
    T09: { title: '앱 언어를 바꿨다가 원래 언어로 되돌리세요.', hint: '설정 > 언어.' },
    T10: { title: 'Instagram 계정을 인증하세요.', hint: '프로필의 "미인증" 배너를 누르고 코드를 복사해 @tora.verify에 DM으로 보내세요.' },
    T11: { title: 'Search에서 지구본을 열고 도시를 눌러 누가 있는지 보세요.', hint: 'Search 탭, 지구본 보기. 핀은 멤버가 있는 도시입니다. 하나를 누르면 그 도시가 열립니다. 목록 보기의 도시 필터도 됩니다.' },
    T12: { title: '다른 프로필에 좋아요를 누르세요.', hint: '프로필 카드의 하트를 누르세요.' },
    T13: { title: '배정된 상대에게 연결 요청을 보내세요.', hint: '상대 프로필을 열고 "연결"을 누른 뒤 짧은 메시지를 쓰세요.' },
    T14: { title: '연결된 멤버에게 메시지를 보내세요.', hint: '메시지 탭, 또는 프로필의 메시지 버튼.' },
    T15: { title: '채팅에서 파일을 보내세요. 어떤 첨부든 괜찮습니다.', hint: '채팅 입력창의 클립 아이콘.' },
    T16: { title: '배정된 상대에게 오퍼를 보내세요.', hint: '상대 프로필이나 채팅을 열고 "오퍼 보내기".' },
    T17: { title: '계약금 기한과 잔금 기한이 포함된 오퍼를 보내세요.', hint: '오퍼 양식 아래쪽의 날짜 입력란 두 개.' },
    T18: { title: '기다리고 있는 오퍼를 열어 조건을 읽으세요.', hint: '예약 탭. 맨 위에 있습니다.' },
    T19: { title: '오퍼에 역제안하세요. 출연료와 다른 조건 하나 이상을 바꾸세요.', hint: '오퍼를 열고 "역제안"을 누르세요.' },
    T20: { title: '오퍼를 수락하세요.', hint: '오퍼 확인 후 수락.' },
    T21: { title: '오퍼를 거절하고 이유를 적으세요.', hint: '오퍼 확인 후 거절.' },
    T22: { title: '합의된 거래의 계약서를 보내세요. 어떤 첨부든 괜찮습니다.', hint: '수락된 예약을 열고 "계약서 보내기" → 아무 파일이나 업로드.' },
    T23: { title: '받은 계약서에 서명하세요.', hint: '예약을 열고 "서명"을 누르세요.' },
    T24: { title: '계약 단계를 건너뛴 뒤 다시 복원하세요.', hint: '예약 카드의 "계약 건너뛰기" → "계약 단계 복원".' },
    T25: { title: '계약금을 송금 완료로 표시하고 영수증을 첨부하세요. 이미지나 PDF면 됩니다.', hint: '예약 카드의 결제 단계.' },
    T26: { title: '결제를 받았음을 확인하세요.', hint: '예약 카드의 결제 단계.' },
    T27: { title: '예약 하나를 끝까지 진행하세요. 첫 메시지부터 확정·결제 완료까지.', hint: '여기엔 지름길이 없습니다. 이게 제품 전체입니다.' },
    T28: { title: '대리를 요청한 에이전트를 수락하세요.', hint: '알림, 또는 그 에이전트와의 채팅.' },
    T29: { title: '프레스 킷과 테크니컬 라이더를 올리세요. 어떤 파일이든 괜찮습니다.', hint: '채팅의 클립, 또는 예약 안의 문서 단계.' },
    T30: { title: '로스터에 아티스트 세 명을 추가하세요.', hint: '프로필 > 소속 아티스트 > 추가. TORA에서 검색하거나 직접 입력하세요.' },
    T31: { title: 'TORA의 아티스트에게 대리 요청을 보내세요.', hint: '상대 프로필에서 "대리 요청".' },
    T32: { title: '아티스트 관리를 열고 할 일 목록의 항목 하나를 처리하세요.', hint: '로스터에서 아티스트의 "관리"를 누르세요. 목록은 위에 있습니다.' },
    T33: { title: '본인이 아니라 대리하는 아티스트 명의로 예약을 협상하세요.', hint: '답할 때 오퍼 주체를 아티스트로 전환하세요.' },
    T34: { title: '메시지로 베뉴에 소속 아티스트를 제안하세요. 베뉴는 오퍼를 받지 않고 보내는 쪽입니다.', hint: '베뉴 프로필을 열고 "제안 보내기". 관심이 있으면 오퍼가 돌아옵니다.' },
    T35: { title: '메시지로 받은 제안에 오퍼를 보내 답하세요.', hint: '채팅을 열고 그 대화에서 "오퍼 보내기".' },
    T36: { title: 'Tour Kickstart에서 투어를 열고 "관심 있어요"를 누르세요.', hint: 'Tour 탭 > Tour Kickstart. 한 번의 탭으로 아티스트는 도시별 관심을 볼 수 있습니다. 투어 중인 아티스트에 좋아요를 누르면 이동 알림도 자동 설정됩니다.' },
    T37: { title: '누군가의 투어에 날짜를 제안하세요.', hint: '탐색 > 투어, 투어를 열고 "날짜 제안".' },
    T39: { title: '수용 인원과 베뉴 정보를 설정하세요.', hint: '프로필 > 편집. 수용 인원, 도시, 장르, 사진.' },
    T40: { title: '기술 사양과 접대 정보를 아티스트와 공유하세요. 어떤 파일이든 괜찮습니다.', hint: '채팅의 클립, 또는 예약 안의 문서 단계.' },
    T41: { title: 'News에 글을 올리세요.', hint: 'News 탭 상단의 작성란.' },
    T42: { title: '다른 사람의 글에 좋아요나 댓글을 남기세요.', hint: '글의 하트 또는 댓글 아이콘.' },
    T43: { title: '알림을 켜고 하나가 도착하는지 확인하세요.', hint: '로그인 후 나타나는 카드, 또는 설정 > 알림. iPhone은 먼저 TORA를 홈 화면에 추가해야 합니다(과제 T01).' },
    T45: { title: '테스트 카드 4242 4242 4242 4242(만료일·CVC는 아무거나)로 Premium으로 업그레이드하세요.', hint: '설정 > Premium, 또는 한도에 도달했을 때 나오는 안내.' },
    T46: { title: '구독을 취소한 뒤, 이용 종료일에 대해 앱이 뭐라고 알려주는지 확인하세요.', hint: '설정 > 구독 관리 > 취소.' },
    'T07@AGENT': { title: '소속 아티스트 한 명의 앞으로 두 달간 가능한 날짜를 표시하세요.', hint: '프로필 > 관리 > 아티스트 선택 > 캘린더. 비어 있는 날짜를 누르세요.' },
    'T08@AGENT': { title: '소속 아티스트 한 명의 이동 일정을 업데이트하세요.', hint: '프로필 > 관리 > 아티스트 선택 > 이동 일정. 도시와 날짜를 추가하세요.' },
    T51: { title: '마지막 질문: 다음 달에 TORA로 실제 예약을 진행하시겠어요? 예/아니오와 그 이유.', hint: '"답하기"를 누르세요. 한 문장이면 충분합니다.' },
  },
};

Object.assign(BETA_UI, {
  it: {
    yourList: 'LA TUA LISTA', tellUs: 'RACCONTACI',
    intro: 'Fai queste attività nell\'ordine che vuoi, in tutte le sessioni che ti servono.',
    showMeHow: 'Mostrami come', confusing: 'Non era chiaro', skip: 'Salta', answer: 'Rispondi',
    skipWhy: 'Perché la salti? Basta una riga.', cancel: 'Annulla', skipIt: 'Salta',
    typeQ: 'Di che si tratta?', howBad: 'Quanto è grave?',
    placeholder: 'Cos\'è successo? Corto e diretto è perfetto: "non capisco cosa fa questo pulsante" è una segnalazione utile.',
    addShot: 'Aggiungi screenshot', autoNote: 'Schermata, dispositivo e ultimo errore vengono allegati in automatico: non serve descriverli.',
    send: 'Invia', received: 'Ricevuto, grazie.', receivedSub: 'Ogni segnalazione migliora TORA. Mandane quante vuoi.',
    sendAnother: 'Inviane un\'altra', aboutTask: 'Attività', remove: 'togli', loading: 'Caricamento…',
    loadError: 'Impossibile caricare la lista.', retry: 'Riprova',
    severities: { blocked: 'Mi ha bloccato', annoyed: 'Mi ha infastidito', noting: 'Solo una nota' },
    inviteUnavailable: 'Non disponibile durante il beta test: il beta è un gruppo chiuso. Invitare amici si sblocca al lancio.',
    finalCheck: 'VERIFICA FINALE', finalIntro: 'Una sola domanda, direttamente dal fondatore. La tua risposta sincera decide cosa costruiamo dopo.',
    yes: 'Sì', no: 'No', whyQ: 'Perché?', whyPlaceholder: 'Basta una frase. Diretto è meglio.',
    finalSend: 'Invia la risposta', finalDone: 'Grazie: era l\'unica risposta che ci serviva.', finalDoneSub: 'La tua lista è completa. Puoi sempre inviare segnalazioni da Raccontaci.',
    backToList: 'Torna alla lista',
  },
  es: {
    yourList: 'TU LISTA', tellUs: 'CUÉNTANOS',
    intro: 'Hazlas en el orden que quieras, en tantas sesiones como necesites.',
    showMeHow: 'Muéstrame cómo', confusing: 'No quedó claro', skip: 'Omitir', answer: 'Responder',
    skipWhy: '¿Por qué la omites? Con una línea basta.', cancel: 'Cancelar', skipIt: 'Omitir',
    typeQ: '¿Qué tipo de cosa?', howBad: '¿Cómo de grave?',
    placeholder: '¿Qué pasó? Corto y directo es perfecto: "no sé qué hace este botón" es un reporte útil.',
    addShot: 'Añadir captura', autoNote: 'La pantalla, el dispositivo y el último error se adjuntan solos: no hace falta describirlos.',
    send: 'Enviar', received: 'Recibido, gracias.', receivedSub: 'Cada reporte mejora TORA. Envía tantos como quieras.',
    sendAnother: 'Enviar otro', aboutTask: 'Sobre la tarea', remove: 'quitar', loading: 'Cargando…',
    loadError: 'No se pudo cargar tu lista.', retry: 'Reintentar',
    severities: { blocked: 'Me bloqueó', annoyed: 'Me molestó', noting: 'Solo lo anoto' },
    inviteUnavailable: 'No disponible durante la beta: la beta es un grupo cerrado. Invitar amigos se desbloquea en el lanzamiento.',
    finalCheck: 'PREGUNTA FINAL', finalIntro: 'Una sola pregunta, directa del fundador. Tu respuesta sincera decide qué construimos después.',
    yes: 'Sí', no: 'No', whyQ: '¿Por qué?', whyPlaceholder: 'Con una frase basta. Directo es mejor.',
    finalSend: 'Enviar mi respuesta', finalDone: 'Gracias: era la única respuesta que necesitábamos.', finalDoneSub: 'Tu lista está completa. Puedes seguir enviando reportes desde Cuéntanos.',
    backToList: 'Volver a tu lista',
  },
  fr: {
    yourList: 'TA LISTE', tellUs: 'DIS-NOUS',
    intro: 'Fais-les dans l\'ordre que tu veux, en autant de fois que tu veux.',
    showMeHow: 'Montre-moi', confusing: 'Ce n\'était pas clair', skip: 'Passer', answer: 'Répondre',
    skipWhy: 'Pourquoi tu passes ? Une ligne suffit.', cancel: 'Annuler', skipIt: 'Passer',
    typeQ: 'De quoi s\'agit-il ?', howBad: 'C\'est grave ?',
    placeholder: 'Que s\'est-il passé ? Court et direct, c\'est parfait : « aucune idée de ce que fait ce bouton » est un signalement utile.',
    addShot: 'Ajouter une capture', autoNote: 'L\'écran, l\'appareil et la dernière erreur sont joints automatiquement : inutile de les décrire.',
    send: 'Envoyer', received: 'Bien reçu, merci.', receivedSub: 'Chaque signalement améliore TORA. Envoies-en autant que tu veux.',
    sendAnother: 'En envoyer un autre', aboutTask: 'À propos de la tâche', remove: 'retirer', loading: 'Chargement…',
    loadError: 'Impossible de charger ta liste.', retry: 'Réessayer',
    severities: { blocked: 'Ça m\'a bloqué', annoyed: 'Ça m\'a agacé', noting: 'Juste pour info' },
    inviteUnavailable: 'Indisponible pendant le bêta-test : la bêta est un groupe fermé. L\'invitation d\'amis s\'ouvre au lancement.',
    finalCheck: 'DERNIÈRE QUESTION', finalIntro: 'Une seule question, directement du fondateur. Ta réponse sincère décide de ce qu\'on construit ensuite.',
    yes: 'Oui', no: 'Non', whyQ: 'Pourquoi ?', whyPlaceholder: 'Une phrase suffit. Direct, c\'est mieux.',
    finalSend: 'Envoyer ma réponse', finalDone: 'Merci : c\'était la seule réponse qu\'il nous fallait.', finalDoneSub: 'Ta liste est terminée. Tu peux toujours envoyer des signalements depuis Dis-nous.',
    backToList: 'Retour à ta liste',
  },
  pt: {
    yourList: 'A TUA LISTA', tellUs: 'CONTA-NOS',
    intro: 'Faz estas tarefas pela ordem que quiseres, em quantas sessões precisares.',
    showMeHow: 'Mostra-me como', confusing: 'Não ficou claro', skip: 'Saltar', answer: 'Responder',
    skipWhy: 'Porque saltas esta? Uma linha chega.', cancel: 'Cancelar', skipIt: 'Saltar',
    typeQ: 'Que tipo de coisa?', howBad: 'Quão grave?',
    placeholder: 'O que aconteceu? Curto e direto é perfeito: "não faço ideia do que este botão faz" é um relato útil.',
    addShot: 'Adicionar captura', autoNote: 'O ecrã, o dispositivo e o último erro são anexados automaticamente: não precisas de os descrever.',
    send: 'Enviar', received: 'Recebido, obrigado.', receivedSub: 'Cada relato melhora o TORA. Envia quantos quiseres.',
    sendAnother: 'Enviar outro', aboutTask: 'Sobre a tarefa', remove: 'remover', loading: 'A carregar…',
    loadError: 'Não foi possível carregar a tua lista.', retry: 'Tentar de novo',
    severities: { blocked: 'Bloqueou-me', annoyed: 'Irritou-me', noting: 'Só a registar' },
    inviteUnavailable: 'Indisponível durante o beta: o beta é um grupo fechado. Convidar amigos desbloqueia no lançamento.',
    finalCheck: 'PERGUNTA FINAL', finalIntro: 'Uma única pergunta, diretamente do fundador. A tua resposta sincera decide o que construímos a seguir.',
    yes: 'Sim', no: 'Não', whyQ: 'Porquê?', whyPlaceholder: 'Uma frase chega. Direto é melhor.',
    finalSend: 'Enviar a minha resposta', finalDone: 'Obrigado: era a única resposta de que precisávamos.', finalDoneSub: 'A tua lista está completa. Podes continuar a enviar relatos em Conta-nos.',
    backToList: 'Voltar à lista',
  },
  zh: {
    yourList: '我的任务', tellUs: '反馈',
    intro: '顺序不限，分几次完成都可以。',
    showMeHow: '看看怎么做', confusing: '这里不好懂', skip: '跳过', answer: '回答',
    skipWhy: '为什么跳过？一句话就够。', cancel: '取消', skipIt: '跳过',
    typeQ: '是哪一类问题？', howBad: '有多严重？',
    placeholder: '发生了什么？简短直接就好——"不知道这个按钮是干嘛的"也是有用的反馈。',
    addShot: '添加截图', autoNote: '页面、设备和最近一次错误会自动附上，不用描述。',
    send: '发送', received: '已收到，谢谢。', receivedSub: '每一条反馈都让 TORA 更好。想发多少都可以。',
    sendAnother: '再发一条', aboutTask: '关于任务', remove: '移除', loading: '加载中…',
    loadError: '无法加载任务列表。', retry: '重试',
    severities: { blocked: '卡住了', annoyed: '有点烦', noting: '随手记一下' },
    inviteUnavailable: '内测期间不可用：内测是封闭小组。邀请好友功能将在正式上线时开放。',
    finalCheck: '最后一问', finalIntro: '创始人只问一个问题。你坦率的回答决定我们接下来做什么。',
    yes: '是', no: '否', whyQ: '为什么？', whyPlaceholder: '一句话就够，直说最好。',
    finalSend: '发送回答', finalDone: '谢谢——这就是我们最想听到的答案。', finalDoneSub: '你的任务已全部完成。随时仍可在"反馈"里给我们留言。',
    backToList: '返回任务列表',
  },
  ko: {
    yourList: '내 목록', tellUs: '알려주기',
    intro: '순서는 자유입니다. 여러 번에 나눠서 진행해도 됩니다.',
    showMeHow: '방법 보기', confusing: '헷갈렸어요', skip: '건너뛰기', answer: '답하기',
    skipWhy: '왜 건너뛰나요? 한 줄이면 됩니다.', cancel: '취소', skipIt: '건너뛰기',
    typeQ: '어떤 종류인가요?', howBad: '얼마나 심각한가요?',
    placeholder: '무슨 일이 있었나요? 짧고 솔직하면 충분합니다. "이 버튼이 뭘 하는지 모르겠다"도 좋은 제보입니다.',
    addShot: '스크린샷 추가', autoNote: '화면, 기기, 마지막 오류는 자동으로 첨부됩니다. 설명하지 않아도 됩니다.',
    send: '보내기', received: '잘 받았습니다. 감사합니다.', receivedSub: '모든 제보가 TORA를 더 좋게 만듭니다. 얼마든지 보내주세요.',
    sendAnother: '하나 더 보내기', aboutTask: '관련 과제', remove: '제거', loading: '불러오는 중…',
    loadError: '목록을 불러오지 못했습니다.', retry: '다시 시도',
    severities: { blocked: '막혔어요', annoyed: '불편했어요', noting: '그냥 메모' },
    inviteUnavailable: '베타 테스트 중에는 사용할 수 없습니다. 베타는 비공개 그룹이며, 친구 초대는 정식 출시 때 열립니다.',
    finalCheck: '마지막 질문', finalIntro: '창업자가 딱 하나만 묻습니다. 솔직한 답이 다음에 만들 것을 결정합니다.',
    yes: '예', no: '아니오', whyQ: '이유는요?', whyPlaceholder: '한 문장이면 됩니다. 솔직할수록 좋습니다.',
    finalSend: '답 보내기', finalDone: '감사합니다. 가장 듣고 싶었던 답입니다.', finalDoneSub: '목록을 모두 마쳤습니다. "알려주기"에서는 언제든 제보할 수 있습니다.',
    backToList: '목록으로 돌아가기',
  },
});
